CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    phone_number VARCHAR(50) NOT NULL,
    is_teacher BOOLEAN NOT NULL DEFAULT FALSE,
    image_path TEXT NOT NULL DEFAULT NULL,
    finger_id TEXT NOT NULL DEFAULT NULL,
    is_biometric_active BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS entrance (
    id INTEGER PRIMARY KEY,
    user_id INTEGER NOT NULL,
    entry_time INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS exit (
    id INTEGER PRIMARY KEY,
    user_id INTEGER NOT NULL,
    exit_time INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS admin (
    user_name VARCHAR(100) PRIMARY KEY,
    password VARCHAR(100) NOT NULL UNIQUE
);
