// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateAttendance(ctx context.Context, arg CreateAttendanceParams) error
	// Roles Queries
	CreateRole(ctx context.Context, roleName string) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteAttendance(ctx context.Context, attendanceID int64) error
	DeleteRole(ctx context.Context, roleID int64) error
	DeleteUser(ctx context.Context, userID int64) error
	GetAllUsersAttendanceByDate(ctx context.Context, date string) ([]GetAllUsersAttendanceByDateRow, error)
	GetAttendanceByUserIDAndDate(ctx context.Context, arg GetAttendanceByUserIDAndDateParams) (Attendance, error)
	GetRoleByID(ctx context.Context, roleID int64) (Role, error)
	GetUserAttendanceBetweenDates(ctx context.Context, userID sql.NullInt64) ([]GetUserAttendanceBetweenDatesRow, error)
	GetUserByID(ctx context.Context, userID int64) (User, error)
	UpdateAttendance(ctx context.Context, arg UpdateAttendanceParams) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
